version: '3.8'

services:
  ctf:
    build: .
    container_name: ctf
    ports:
      - "8080:80"
      - "5353:5353"
      - "22:22"
    volumes:
      - ./Code:/var/www/html
    hostname: umbrella.com
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gottheevidence
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  db-data:
